### PR TITLE
Remove 5531

### PR DESCRIPTION
**Pull request by ct-clearhaus**
Visa has removed 5531 and recommends 5533 as a substitute.

Closes https://github.com/clearhaus/issues-nonpci/issues/363.

### CODE REVIEW

**Comment by jsmpereira** [comment]
I suppose that since this is coming from Visa this approach makes sense.

Previously, as in https://github.com/clearhaus/dinghy/pull/8, we blacklisted `6011`, but in that case it was about our internal business rules to decide not to provide that `6011`.

@ct-clearhaus @mathiaslm89

**Comment by jsmpereira** [comment]
@ct-clearhaus Did we get this info from a Visa Merchant Data Standards update? Can we link the document here for reference?

**Comment by ct-clearhaus** [comment]
RMG didn't have a reference (although there quite certainly is one), but just noticed that 5531 is not in the list from Visa anymore; because the clearing of a transaction with 5531 was rejected by Visa.

**Comment by jsmpereira** [comment]
@ct-clearhaus if you could take a quick 👀 🙇

**Review by ct-clearhaus — COMMENTED** [review]
👍
Although I haven't inspected the entire diff 🙂

**Pull request merged**
