### PR TITLE
October 2016 updates

### PR DESCRIPTION
**Pull request by ct-clearhaus**
Also add 3832 and 3833 to mcc_codes.json.

RFR @jsmpereira

### CODE REVIEW

**Comment by jsmpereira** [comment]
I remembered there was also an issue with MCC [5531](https://github.com/clearhaus/mcc-codes/blob/master/mcc_codes.csv#L772) which seems to be MasterCard exclusive. We've had some issues with that one being assigned to some merchants and when a VISA card hits, breakage.

It seems that either [5532](https://github.com/clearhaus/mcc-codes/blob/master/mcc_codes.csv#L773) or [5533](https://github.com/clearhaus/mcc-codes/blob/master/mcc_codes.csv#L774) might be acceptable alternatives, and from what I understand the risk managers have been using them, but from time to time a 5531 slips in.

The easy fix would be to just remove it, for consistency. Otherwise other more _intricate_ solutions might be brainstormed (not sure if worth the effort) 😛

**Comment by jsmpereira** [comment]
Closed https://github.com/clearhaus/issues-nonpci/issues/172 because I forgot to check this one.

Gitte was mentioning the need for `6540` and I didn't look too close.

But the reference I got was 

> MCC 6540 - POI (Point of Interaction) Funding Transactions (Excluding MoneySend).

while the PR has

> 6540,Stored Value Card,Stored Value Card,Non-Financial Institutions – Stored value Card Purchase/load

@ct-clearhaus Do you have handy the doc for these updates?

**Comment by ct-clearhaus** [comment]
I'm unable to find a Visa Merchant Data Standards Manual that includes the MCC updates. Also, the latest Visa Europe Operating Regulations isn't too informative in this regard. Though, I found this:

> Effective from 15 October 2016, a Merchant whose primary business is the sale of
> Prepaid Cards must use the Merchant Category Code (MCC) 6540 for the purchase
> and reloading of Prepaid Cards.

I do not know which one is the more correct description.

Re. MCC 5531: Let's just remove it---and make no upstream PR, but maybe an issue?

**Comment by jsmpereira** [comment]
@ct-clearhaus 
I've found 6540 and 3300 on https://usa.visa.com/dam/VCOM/download/merchants/visa-merchant-data-standards-manual.pdf (Nov 2016), supporting the changes from this PR. 

screen shot 2017-03-20 at 13 31 05

https://github.com/clearhaus/mcc-codes/pull/8 seems to point to what should be Mastercard only MCC. I've found it on https://www.mastercard.us/content/dam/mccom/en-us/documents/rules/quick-reference-booklet-me-nov_2015.pdf (page 137) - seems to be most recent as per https://www.mastercard.us/en-us/about-mastercard/what-we-do/rules.html.

screen shot 2017-03-20 at 13 32 21
screen shot 2017-03-20 at 13 32 26

**Comment by RTPeat** [comment]
6540 is in the set of changes from pull request #9 that has just merged in - 3300 is missing though.

**Comment by jsmpereira** [comment]
@RTPeat Doesn't seem that it's there. 

The last updated MCC is `3835`, at https://github.com/clearhaus/mcc-codes/pull/9/files#diff-f8ab42f19cd67c3e09b8264a892ebc1aR740.

**Comment by RTPeat** [comment]
Yes - didn't go in with #9 then, but is definitely in the CSV file.

**Comment by jsmpereira** [comment]
Indeed :)

> #8 seems to point to what should be Mastercard only MCC.

_in_ https://github.com/clearhaus/mcc-codes/pull/7#issuecomment-287743801.

**Comment by jsmpereira** [comment]
`6540` added in https://github.com/clearhaus/mcc-codes/pull/8.

`3832` and `3833` added in https://github.com/clearhaus/mcc-codes/pull/6.

Only `3300` is unaccounted for elsewhere.

@ct-clearhaus Should we modify this PR to only address `3300` or close and make a new one?

**Comment by ct-clearhaus** [comment]
> Should we modify this PR to only address `3300` or close and make a new one?

Whatever you prefer 🙂

**Comment by jsmpereira** [comment]
> Whatever you prefer 🙂

Damn you! :stuck_out_tongue: 

Closing. Let's make a new PR to add `3300`.

**Pull request closed without merging**
