### PR TITLE
Remove 7332

### PR DESCRIPTION
**Pull request by ct-clearhaus**
We have received a reject from Mastercard for MCC 7332. Recommended substitute unknown.

### CODE REVIEW

**Comment by jsmpereira** [comment]
I was inclined to suggest that we blacklist in https://github.com/clearhaus/dinghy instead of removing here, since it seemed to me from the RAM ticket that it might've been a case of a dedicated VISA mcc being assigned, and of course not working for Mastercard.

However, in https://usa.visa.com/dam/VCOM/download/merchants/visa-merchant-data-standards-manual.pdf (the most recent I could find, 14 Oct 2017) there is a jump from  `7321 Consumer Credit Reporting Agencies` to  `7333 Commercial Photography, Art, and Graphics`, so I suppose `7332`  can just be removed.

The PR only changes `.csv`, while `dinghy` makes use of `.json` (https://github.com/clearhaus/dinghy/blob/master/lib/dinghy.rb#L13). 

Should I generate the missing formats? :)

**Comment by ct-clearhaus** [comment]
> Should I generate the missing formats? :)

I’d be thankful. It also holds true for at least one other PR here.

**Comment by jsmpereira** [comment]
I'll update https://github.com/clearhaus/mcc-codes/pull/12 once this PR is merged to not have to deal with a merge conflict with the shifting ids in the files.

**Comment by ct-clearhaus** [comment]
:+1:

Feel free to merge.

**Pull request merged**
